"""HTML Export — standalone report page."""

from __future__ import annotations

from datetime import datetime

from app.models.page import PageData
from app.models.project import ProjectConfig


def generate_html_report(project: ProjectConfig, pages: list[PageData]) -> str:
    """Generate a standalone HTML report string.

    Args:
        project: Project configuration.
        pages: Analysed pages.

    Returns:
        Complete HTML string.
    """
    now = datetime.now().strftime("%d %B %Y, %H:%M")
    scores = [int(p.scores.total) for p in pages if p.extraction_complete]
    avg_score = sum(scores) // len(scores) if scores else 0

    pages_html = "".join(_page_section(p) for p in pages)

    return f"""<!DOCTYPE html>
<html lang="de">
<head>
<meta charset="utf-8">
<title>SEOOptimize — {project.business_name}</title>
<style>
  body {{ font-family: system-ui, sans-serif; max-width: 900px; margin: 0 auto; padding: 2rem; color: #0F172A; }}
  h1 {{ color: #1E40AF; }}
  h2 {{ color: #1E40AF; border-bottom: 2px solid #E2E8F0; padding-bottom: 0.5rem; }}
  .score {{ font-size: 3rem; font-weight: 800; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
  th {{ background: #F1F5F9; padding: 8px; text-align: left; font-size: 0.8rem; }}
  td {{ padding: 6px 8px; border-bottom: 1px solid #F1F5F9; font-size: 0.85rem; }}
  .pass {{ color: #16A34A; font-weight: 600; }}
  .warn {{ color: #D97706; font-weight: 600; }}
  .fail {{ color: #DC2626; font-weight: 600; }}
  .rec {{ border-left: 3px solid #E2E8F0; padding: 8px 12px; margin: 0.5rem 0; }}
  .rec-critical {{ border-left-color: #DC2626; background: #FEF2F2; }}
  .rec-warning {{ border-left-color: #D97706; background: #FFFBEB; }}
  .rec-quick_win {{ border-left-color: #16A34A; background: #F0FDF4; }}
  footer {{ text-align: center; color: #94A3B8; font-size: 0.75rem; margin-top: 3rem; }}
</style>
</head>
<body>
<h1>SEOOptimize — {project.business_name}</h1>
<p><strong>Website:</strong> {project.website_url} &nbsp;|&nbsp;
<strong>City:</strong> {project.target_city} &nbsp;|&nbsp;
<strong>Generated:</strong> {now}</p>

<h2>Site Score: <span class="score" style="color:{'#16A34A' if avg_score >= 70 else '#D97706' if avg_score >= 45 else '#DC2626'}">{avg_score}</span>/100</h2>

{pages_html}

<footer>Generated by SEOOptimize v1.0</footer>
</body>
</html>"""


def _page_section(page: PageData) -> str:
    score = int(page.scores.total)
    short_url = page.url.replace("https://", "").replace("http://", "")

    fields = [
        ("Meta Title", page.extracted.meta_title),
        ("Meta Description", page.extracted.meta_description),
        ("H1", page.extracted.h1),
        ("H2 Structure", page.extracted.h2_structure),
        ("Word Count", page.extracted.word_count),
        ("Images Alt", page.extracted.images_with_alt),
        ("Phone Above Fold", page.extracted.phone_above_fold),
        ("Schema", page.extracted.schema_markup),
        ("Canonical", page.extracted.canonical_tag),
        ("Mobile Viewport", page.extracted.mobile_viewport),
        ("NAP", page.extracted.nap_on_page),
        ("Internal Links", page.extracted.internal_links),
        ("Load Time", page.extracted.page_load_time),
        ("HTTPS", page.extracted.https),
    ]

    field_rows = "\n".join(
        f"<tr><td>{label}</td>"
        f"<td class='{f.status.value}'>{f.status.value.upper()}</td>"
        f"<td>{str(f.value or '')[:80]}</td>"
        f"<td style='color:#64748B;font-size:0.8rem;'>{f.note or ''}</td></tr>"
        for label, f in fields
    )

    cards_data = page.ai_analysis.get("recommendation_cards", [])
    rec_html = ""
    if cards_data:
        rec_html = "<h3>Recommendations</h3>"
        for card in cards_data[:10]:
            priority = card.get("priority", "warning")
            rec_html += f"""
<div class="rec rec-{priority}">
  <strong>[{priority.upper()}] {card.get('label', '')}</strong><br>
  {card.get('problem', '')}<br>
  <em>Fix: {card.get('suggested_fix', '')[:150]}</em>
</div>"""

    return f"""
<hr>
<h2>{short_url} — {score}/100</h2>
<table>
  <tr><th>Field</th><th>Status</th><th>Value</th><th>Note</th></tr>
  {field_rows}
</table>
{rec_html}"""
